name: Create Archive
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'resource-pack-galith.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig README.md docs/*'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'resource-pack-galith.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
