on:
  release:
    types: [published]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:

      - name: Build & Upload Packs
        uses: Sindercube/Packr@v2
        with:

          github-repo: ${{ github.event.repository.full_name }}
          release-version: ${{ github.event.release.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
